export const GET_CARS = 'GET_CARS'
export const GET_MYCARS = 'GET_MYCARS'
export const GET_LAST20CARS = 'GET_LAST20CARS'
export const GET_CAR = 'GET_CAR'
export const ADD_CAR = 'ADD_CAR'
export const DELETE_CAR = 'DELETE_CAR'
export const EDIT_CAR = 'EDIT_CAR'
export const CARS_LOADING = 'CARS_LOADING'
export const CAR_ERROR = 'CAR_ERROR'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_ERROR = 'USER_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'